FROM jolielang/jolie:edge-alpine

WORKDIR /app
COPY *.ol /app

EXPOSE 8001
ENV PROVISIONER_LOCATION "socket://0.0.0.0:8001"
ENV FUNCTION_CATALOG_LOCATION "socket://function_catalog:8002"
ENV JOCKER_LOCATION "socket://jocker:8008"

ENV DOCKER_NETWORK "jfn"
ENV CALLS_PER_RUNNER 1
ENV CALLS_FOR_PROMOTION 2
ENV MIN_RUNNERS 2

ENV VERBOSE false
ENV DEBUG   false

CMD jolie provisioner_loader.ol
