FROM jolielang/jolie:edge-alpine

WORKDIR /app
COPY function_catalog.ol function_catalog.ol
COPY runner.ol runner.ol
COPY function_catalog.ol function_catalog.ol
COPY docker/gateway_params.json params.json

EXPOSE 8010

CMD jolie --params params.json runner.ol
