FROM jolielang/jolie:edge-alpine

WORKDIR /app
RUN apk add --no-cache openjdk11

COPY *.ol /app
COPY docker/function_catalog_params.json params.json

RUN javac -cp /usr/lib/jolie/jolie.jar jfn/Checksum.java
RUN jar cvf checksum.jar jfn/Checksum.class
RUN mkdir lib && mv checksum.jar lib/checksum.jar

RUN apk del openjdk11

EXPOSE 6000
ENV VERBOSE false
VOLUME /data

CMD jolie function_catalog.ol
