version: "3.9"
services:
  jocker:
    image: jolielang/jocker
    volumes:
      - /var/run:/var/run
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  catalog:
    image: jfn/function_catalog
    build: # comment out this line in production
      context: ..
      dockerfile: docker/Dockerfile.function_catalog
    volumes:
      - ../functions:/app/functions

  provisioner:
    image: jfn/provisioner
    build: # comment out this line in production
      context: ..
      dockerfile: docker/Dockerfile.provisioner
    environment:
      VERBOSE: true
      RUNNER_LOCATION: "socket://provisioner:8060"
      JOCKER_LOCATION: "socket://jocker:8008"
    depends_on:
      - jocker

  gateway:
    image: jfn/gateway
    build: # comment out this line in production
      context: ..
      dockerfile: docker/Dockerfile.gateway
    ports:
      - 8000:8000
    depends_on:
      - provisioner

  runner:
    image: jfn/runner
    build: # comment out this line in production
      context: ..
      dockerfile: docker/Dockerfile.runner
    environment:
      VERBOSE: true
      RUNNER_LOCATION: "socket://runner:8010"
      FUNCTION_CATALOG_LOCATION: "socket://catalog:6000"
      PROVISIONER_LOCATION: "socket://provisioner:8000"
    depends_on:
      - provisioner
      - catalog
