FROM jolielang/jolie:edge-alpine

WORKDIR /app
RUN apk add --no-cache openjdk11

COPY *.ol /app
RUN mkdir jfn
COPY Checksum.java /app/jfn

RUN javac -cp /usr/lib/jolie/jolie.jar jfn/Checksum.java
RUN jar cvf checksum.jar jfn/Checksum.class
RUN mkdir lib && mv checksum.jar lib/checksum.jar

RUN apk del openjdk11

VOLUME /data
EXPOSE 8002
ENV FUNCTION_CATALOG_LOCATION "socket://0.0.0.0:8002"
ENV VERBOSE false

CMD jolie function_catalog.ol
