FROM jolielang/jolie:edge-alpine

WORKDIR /app
COPY function_catalog.ol function_catalog.ol
COPY docker/function_catalog_params.json params.json

EXPOSE 6000
VOLUME /data

CMD jolie --params params.json function_catalog.ol
